---
title: "PA1_template"
author: "Catalina Herrera"
date: "February 4, 2016"
output: html_document
---

```{r}
library(knitr)
library(dplyr)
library(ggplot2)
opts_chunk$set(echo = TRUE)
# set up working directory
setwd("C:/Users/cherrera/Desktop/R working Directory")
# load data
data_row <- read.csv('C:/Users/cherrera/Desktop/R working Directory/data/repdata-data-activity/activity.csv')
# remove NA in data
data <- data_row[ with (data_row, { !(is.na(steps)) } ), ]

# print out first 20 rows
head(data,20)

#What is mean total number of steps taken per day
#Calculate the total number of steps taken per day
by_day <- group_by(data, date)
steps_by_day <- summarise(by_day, total = sum(steps))
steps_by_day

#If you do not understand the difference between a histogram and a barplot, research the difference between them. 
#Make a histogram of the total number of steps taken each day

hist(steps_by_day$total, main="Histogram of total number of steps per day", 
     xlab="Total number of steps in a day")

#Calculate and report the mean and median of the total number of steps taken per day
summary(steps_by_day)

#What is the average daily activity pattern?
#Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average 
#number of steps taken, averaged across all days (y-axis)
steps_by_interval <- aggregate(steps ~ interval, data, mean)
plot(steps_by_interval$interval, steps_by_interval$steps, type='l', 
     main="Average number of steps over all days", xlab="Interval", 
     ylab="Average number of steps")

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
# find row with max of steps
max_steps_row <- which.max(steps_by_interval$steps)

# find interval with this max
steps_by_interval[max_steps_row, ]

#Imputing missing values

#Note that there are a number of days/intervals where there are missing 
#values (coded as NA). The presence of missing days may introduce bias 
#into some calculations or summaries of the data.

#Calculate and report the total number of missing values in the dataset 
#(i.e. the total number of rows with NAs)
sum(is.na(data_row))
#Devise a strategy for filling in all of the missing values in the dataset. 
#The strategy does not need to be sophisticated. For example, you could use 
#the mean/median for that day, or the mean for that 5-minute interval, etc.
#####replacing NA's with the mean for that 5-minute interval.
data_imputed <- data_row
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value <- data_imputed$interval[i]
    steps_value <- steps_by_interval[
      steps_by_interval$interval == interval_value,]
    data_imputed$steps[i] <- steps_value$steps
  }
}



#Create a new dataset that is equal to the original dataset but with the 
#missing data filled in.
# calculate  total number of steps taken each day

df_imputed_steps_by_day <- aggregate(steps ~ date, data_imputed, sum)
head(df_imputed_steps_by_day)

#Make a histogram of the total number of steps taken each day and 
#Calculate and report the mean and median total number of steps taken 
#per day. Do these values differ from the estimates from the first part 
#of the assignment? What is the impact of imputing missing data on the 
#estimates of the total daily number of steps?

hist(df_imputed_steps_by_day$steps, main="Histogram of total number of steps per day (imputed)", 
     xlab="Total number of steps in a day")

# get mean and median of imputed data
mean(df_imputed_steps_by_day$steps)

median(df_imputed_steps_by_day$steps)

# get mean and median of data without NA's
mean(steps_by_day$total)
median(steps_by_day$total)

#Are there differences in activity patterns between weekdays and weekends?

#Create a new factor variable in the dataset with two levels - "weekday" and "weekend" 
#indicating whether a given date is a weekday or weekend day.

#Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute 
#interval (x-axis) and the average number of steps taken, averaged across all weekday 
#days or weekend days (y-axis). See the README file in the GitHub repository to see an 
#example of what this plot should look like using simulated data.

data_imputed['type_of_day'] <- weekdays(as.Date(data_imputed$date))
data_imputed$type_of_day[data_imputed$type_of_day  %in% c('Saturday','Sunday') ] <- "weekend"
data_imputed$type_of_day[data_imputed$type_of_day != "weekend"] <- "weekday"
# convert type_of_day from character to factor
data_imputed$type_of_day <- as.factor(data_imputed$type_of_day)

# calculate average steps by interval across all days
df_imputed_steps_by_interval <- aggregate(steps ~ interval + type_of_day, data_imputed, mean)

# creat a plot
qplot(interval, 
      steps, 
      data = df_imputed_steps_by_interval, 
      geom=c("line"),
      xlab = "Interval", 
      ylab = "Number of steps", 
      main = "") +
  facet_wrap(~ type_of_day, ncol = 1)
```

You can also embed plots, for example:

```{r, echo=FALSE}
hist(steps_by_day$total, main="Histogram of total number of steps per day", 
     xlab="Total number of steps in a day")

plot(steps_by_interval$interval, steps_by_interval$steps, type='l', 
     main="Average number of steps over all days", xlab="Interval", 
     ylab="Average number of steps")

hist(df_imputed_steps_by_day$steps, main="Histogram of total number of steps per day (imputed)", 
     xlab="Total number of steps in a day")

qplot(interval, 
      steps, 
      data = df_imputed_steps_by_interval, 
      geom=c("line"),
      xlab = "Interval", 
      ylab = "Number of steps", 
      main = "") +
  facet_wrap(~ type_of_day, ncol = 1)

```


